[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

mainnet = "https://rpc.ankr.com/eth"
sepolia = "https://rpc.sepolia.org"
goerli = "https://rpc.ankr.com/eth_goerli"
arbitrum = "https://rpc.ankr.com/arbitrum"
arbitrumGoerli = "https://arbitrum-goerli.public.blastapi.io"
optimism = "https://rpc.ankr.com/optimism"
optimismGoerli = "https://optimism-goerli.public.blastapi.io"
polygon = "https://rpc.ankr.com/polygon"
polygonMumbai = "https://rpc.ankr.com/polygon_mumbai"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config